In [1]:
from random import choice, randint, randrange
import numpy as np
import tensorflow as tf

In [2]:
def randomMutations(rna, numberOfMutations):
    rnaList = list(rna)
    for i in range(numberOfMutations):
        rnaList[randrange(len(rna))] = choice("ACGT")
    return "".join(rnaList)

In [3]:
def cutIntoReads(rna, length, amount):
    rnaReads = [[]]*amount;
    for i in range(amount):
        firstIndex = 0
        lastIndex = randint(1, length-1)
        provRnaReads = []
        while(lastIndex < len(rna)):
            provRnaReads.append(rna[firstIndex:lastIndex])
            firstIndex = lastIndex
            lastIndex += length + int(np.random.normal(0, length*0.2, 1)[0])
        provRnaReads.append(rna[firstIndex:len(rna)])
        rnaReads[i] = provRnaReads 
    return rnaReads

In [4]:
def createRandomRNASequence(length):
    rna=""
    for count in range(length):
        rna += choice("ACGT")
    return rna

In [5]:
 def switcher(base):
    return {
        'A': 0.,
        'C': 1.,
        'G': 2.,
        'T': 3.
    }.get(base, -1.)     
        
def encryptRnaReads(allRnaReads):
    encryptedReads = []
    for rnaReads in allRnaReads:
        for singleRead in rnaReads:
            singleReadList = list(singleRead)
            singleReadEncrypted = []
            for base in singleReadList:
                singleReadEncrypted.append(switcher(base))
#             print(singleRead)
# #             print(''.join(singleReadEncrypted))
#             print(singleReadEncrypted)
            encryptedReads.append(singleReadEncrypted)
            print(encryptedReads)
    return encryptedReads

In [6]:
rnaReads = cutIntoReads(createRandomRNASequence(10), 10, 2)
encrypedReads = encryptRnaReads(rnaReads)
for read in encrypedReads:
#     read = np.array(read)
#     read[0] = -1
#     read = np.array(read)
    read = tf.cast(read, tf.int32)

    print(read)
    tensorRead = tf.one_hot(read,depth=4)
    print(tensorRead)


[[3.0, 1.0]]
[[3.0, 1.0], [2.0, 1.0, 3.0, 1.0, 1.0, 3.0, 3.0, 2.0]]
[[3.0, 1.0], [2.0, 1.0, 3.0, 1.0, 1.0, 3.0, 3.0, 2.0], [3.0, 1.0, 2.0, 1.0, 3.0, 1.0, 1.0, 3.0]]
[[3.0, 1.0], [2.0, 1.0, 3.0, 1.0, 1.0, 3.0, 3.0, 2.0], [3.0, 1.0, 2.0, 1.0, 3.0, 1.0, 1.0, 3.0], [3.0, 2.0]]
tf.Tensor([3 1], shape=(2,), dtype=int32)
tf.Tensor(
[[0. 0. 0. 1.]
 [0. 1. 0. 0.]], shape=(2, 4), dtype=float32)
tf.Tensor([2 1 3 1 1 3 3 2], shape=(8,), dtype=int32)
tf.Tensor(
[[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]], shape=(8, 4), dtype=float32)
tf.Tensor([3 1 2 1 3 1 1 3], shape=(8,), dtype=int32)
tf.Tensor(
[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]], shape=(8, 4), dtype=float32)
tf.Tensor([3 2], shape=(2,), dtype=int32)
tf.Tensor(
[[0. 0. 0. 1.]
 [0. 0. 1. 0.]], shape=(2, 4), dtype=float32)


In [7]:
rna1 = createRandomRNASequence(10)

rna2 = randomMutations(rna1,2)

print(rna1)
print(rna2)

TCCATATCGT
TCCATATCGA
